export const Q_COPY = {
  title: 'THE DEUTSCH–JOZSA ALGORITHM',
  name: 'Deutsch–Jozsa algorithm.',
  short: 'Deutsch–Jozsa',
  run: 'RUN DEUTSCH-JOZSA',
  mode: 'QUANTUM MODE',
  enter: 'ENTER QUANTUM MODE',
  queries: 'QUANTUM ORACLE QUERIES',
  system: 'QUANTUM SYSTEM',
  oracle: 'Quantum Oracle',
  sup: 'SUPERPOSITION',
  prep: 'PREPARE',
  or: 'ORACLE',
  inter: 'INTERFERENCE',
  meas: 'MEASURE',
  c: 'CONSTANT',
  b: 'BALANCED',
  p: 'Phaser',
  exp1: 'You did not determine the rule by checking every input.',
  exp2: 'The experiment used interference to distinguish the two promised cases.',
};
